### PR TITLE
inline latest ExtUtils::HasCompiler via [DynamicPrereqs]

### PR DESCRIPTION
**Pull request by karenetheridge**
Inlining vs. using a configure-requires dependency, as recommended by @leont.
This version includes the noexec /tmp fix.
Additionally, the fallback prereq hash is also updated in Makefile.PL, and
conflicting versions checked for.  PUREPERL_ONLY is also checked.

(This uses a dev version of DynamicPrereqs, but it should be going stable very soon now.)

### CODE REVIEW

**Comment by autarch** [comment]
This won't pass Travis until the DynamicPrereqs version is non-trial. I'll wait til then to apply. Thanks!

**Comment by karenetheridge** [comment]
I've now released 0.028 as a stable release.

**Comment by autarch** [comment]
I merged this from the CLI. Thanks!

**Comment by karenetheridge** [comment]
cool! let me know if you see anything different in cpantesters or whatever.. it _should_ come out the same, but you never know :)

**Comment by karenetheridge** [comment]
please hold off on releasing this for now -- there are some possible regressions in ModuleIncluder (the role I am using to inline EUHC) that is putting mroe things into inc/ than it should. I will update with more details soon as I confirm them.

**Comment by karenetheridge** [comment]
ok you should be fine as long as ModuleIncluder is version 0.05, not the latest 0.06...  but I'll be fixing this soon (hopefully) and getting a 0.07 out.

**Comment by autarch** [comment]
I installed includer 0.005 and I'm still seeing warnings.pm in the inc dir. That can't be right, can it?

**Comment by karenetheridge** [comment]
0.004 is ok, but 0.005 is not. The root problem is actually in Module::CoreList -- in 0.005 I submitted a change to switch from poking into Module::CoreList internals to using Module::CoreList::is_core(), and the latter has an off-by-one error.

Hopefully we can get this fixed soon and then ModuleIncluder can depend on the fixed MCL.

In the meantime I'm going to release a new DynamicPrereqs that disables the scan-for-prereqs feature, and then I'll patch MCL and ModuleIncluder.

**Comment by karenetheridge** [comment]
Ok, DynamicPrereqs 0.029 is released, including some additional tests to look for unwanted crud in inc/.  You should be good to go now, and I'll pursue further fixes upstream.

**Comment by karenetheridge** [comment]
and also: https://rt.perl.org/rt3/Ticket/Display.html?id=128089

**Comment by autarch** [comment]
So now I'm getting some confusing travis failures - https://travis-ci.org/houseabsolute/List-SomeUtils/jobs/128440848

I tried add a bit to install ExtUtils::HasCompiler explicitly before the `build-dist` line but that doesn't seem to help. Any ideas? Have you seen this elsewhere?

**Comment by karenetheridge** [comment]
I don't understand how the travis-helpers work; it looks like EUHC is being installed into a different perl than what `build-dist` is using...

but from the output, it's installing everything used directly by `dist.ini` -- so probably just an authordep is missing?  (DynamicPrereqs does inject EUHC as a develop prereq, but that's not soon enough for travis.)

**Pull request closed without merging**
